= Junit5 Vanilla Java Tests

This project contains simple tests of Github rest api written on Junit5 with vanilla Java (no Spring)

== Used technologies

1. Junit5 (test framework)
2. Retrofit (REST client)

== Project structure

2 test classes are available:

_EchoTest_ - Jnit5 tests for `Hello, World!` with Nested and Parametrized tests

_GithubApiTest_ - Jnit5 tests for github rest api in BDD style with steps defined in _RepoSteps.class_ and _ForkSteps.java_ and _StepsParameterResolver.java_ for dependency injection to test class.

Tests are executed in parallel on class level, i.e. test methods from the same class executed in parallel, test classes executed sequentially.

_TestRunner.java_ - main class, that start execution of all tests

Preparing executable jar with dependencies for test execution with _maven-assembly-plugin_

=== How to run
1. `mvn clean package` - to build the project and prepare jar
2. `java -javaagent:"org/aspectj/aspectjweaver/1.9.5/aspectjweaver-1.9.5.jar" -jar target/junit5-vanila-java-1.0-SNAPSHOT-jar-with-dependencies.jar` - to start execution

NOTE: add _-Dgithub.token=<your_token>_ to make authorized requests to Github api as a workaround for request limits (https://developer.github.com/v3/#rate-limiting[see more about github limits)]

3. `mvn allure:report` - to generate allure report

NOTE: _Aspectjweaver_ is required for correct allure reporting. Without it BDD-style steps will be missed in the report

=== Found issues
* Created custom _StepsParameterResolver.java_ to resolve dependencies on steps. In case if some new step is added, the resolver should be updated accordingly
* No other dependency injection available
